### ISSUE TITLE
Changing the value of "Free Surface detection threshold" not possible

### ISSUE THREAD

**Issue by moroth89** [DualSPHysics/DesignSPHysics#44] opened 2020-01-18 13:28 UTC
Hello, 

I want to report an error.It is not possible to change the Free Surface detection threshold value in "Execution Parameters". 

The error message is displayed:

DesignSPHysics version: 0.6.0.2001-17-2
Platform: Windows-10-10.0.18362
FreeCAD Version: 0.18.4 (GitTag)
Exception type: <class 'ValueError'>
Exception value: invalid literal for int() with base 10: '2.75'
Traceback:

Kind regards
Moritz

**Comment by zlotny** [comment] 2020-01-20 09:27
Hi there! indeed there was a bug. The GUI was trying to understand the ShiftTFS value as an integer when it's clearly a float number.

The issue is now fixed in the commit 0bcb0b926b63d6cdb87a4b2ec6dd9109c92b327a in the master branch.

You can update DesignSPHyiscs downloading it from the addon manager again and the issue should be fixed.

Thanks for contributing! :)

**Closed by zlotny** 2020-01-20 09:27 UTC

**Comment by moroth89** [comment] 2020-01-21 02:51
Thanks a lot!
