### ISSUE TITLE
Non Primitive Shapes made on freecad are fixed as FillMode: face. 

### ISSUE THREAD

**Issue by prashant111192** [DualSPHysics/DesignSPHysics#17] opened 2019-06-17 15:50 UTC
I am trying to simulate the mixing of fluids inside a specific shaped tank but when I to add the tank to the DSPH simulation the Fill Mode is fixed as _face_. This means that even the Fluid that I Model based on the shape of the tank is a face. 

I have tried using STL and it gives the same issue. I can only specify the fill mode when i use primitive shapes such as, cylinder, cube.... and it is impossible for me to design the tank based on that. Even if somehow I do, in order to create the empty space in the tank i would have to use "cut" on FreeCAD and this would mean that the whole shape would be treated as a shell. 

I was wondering on know how to conduct such simulations on complex shapes. 

Thanks in advance.

**Comment by CirclestheSecond** [comment] 2019-06-17 16:23
When you import an .STL file, the points are created on faces because that’s the only available information. You then could add a fillbox to fill it with fluid particles. 
If you have a shell not a solid, you could convert it to solid using “convert to solid” option under “Part”.

**Comment by zlotny** [comment] 2019-07-01 12:22
@prashant111192 All the shapes and objects defined in FreeCAD have to be translated to the XML needed for GenCase to work. Doing complex shapes on means that in order to translate that to the XML in an exact way we have to export the mesh to STL and then reference it in the XML to GenCase. 

GenCase has a limitation with this types of objects as it does only know where the faces are so DesignSPHysics is made with that restriction in mind. That's basically the reason why that happens.

To work around that, as @CirclestheSecond suggested, you can use a fillbox to "seed particles inside the volume of your shape". A FillBox basically has a seed point and an outer boundary, so it fills from that point with particles until a limit is reached: The mesh of your complex object or the outer bounds.

I hope this is a solution to your problem. Also we're working on implementing an "autofill" feature but in the case of a generally hollow object (like a tank) it will probably not work as intended, so one or multiple fillboxes keeps being the general approach on GenCase/DualSPHysics here.

**Comment by zlotny** [comment] 2019-09-06 08:17
Closing this, seems resolved as there's no comment on it.

**Closed by zlotny** 2019-09-06 08:17 UTC
