### ISSUE TITLE
Some boundary particle exceed the X and Y limit

### ISSUE THREAD

**Issue by eleclizard** [DualSPHysics/DesignSPHysics#62] opened 2020-03-09 04:41 UTC
Hi,

I have been trying to create a simulation of a rotating drum containing water. The way I have defined it I defined a cylinder, make it a face. Then I define a fill box to fill water in. The motion of the cylinder is defined as a rotation motion.

After running GenCase, it came up wit this error: "Some boundary particle exceeded the -X limit (left limit) of the simulation domain.
Some boundary particle exceeded the +X limit (right limit) of the simulation domain.
Some boundary particle exceeded the -Z limit (bottom limit) of the simulation domain.
Some boundary particle exceeded the +Z limit (top limit) of the simulation domain."

Below is the DesignSHPysics folder.

Thank you for your help!
[RotatingDrum.zip](https://github.com/DualSPHysics/DesignSPHysics/files/4304681/RotatingDrum.zip)

**Comment by zlotny** [comment] 2020-03-09 08:30
Hi there. I downloaded your case and executed GenCase. No errors were found:

![image](https://user-images.githubusercontent.com/6155245/76195106-e07f4c00-61e7-11ea-916e-c3d29759811e.png)

However with the issue you're having it seems the problem is in an incorrect definition of the case, not in a bug or issue with the graphical user interface.

Also you didn't attach the XML file generated by GenCase so I couldn't check if it indeed was an error generating it, althought I'm quite sure the XML rendering code for that part is ok.

My only possible solution to that is that you increase the limits of your simulation domain in Execution Parameters (at the bottom) by a certain percentage to check if that solves anything. 

However the actual simulation domain (not the case limits) is not computed until you run DualSPHyiscs, and you said the error spawns after running GenCase. Sounds weird.

Let me know if changing the simulation domain solves anything. If not please ask a question in the DualSPHysics Forums (forums.dual.sphysics.org) as this problem does not seem related to my GUI code and I'm not an experienced user with DualSPHysics.

**Comment by eleclizard** [comment] 2020-03-09 11:57
Hi,

I think I must have mistyped the problem. Actually, running GenCase was fine for me. However, the actual problem starts when I start running DualSHPysics and try to solve the simulation. It will then generate a few initial part files and stop with the error that I mentioned.

Thank you

**Comment by zlotny** [comment] 2020-03-09 12:11
Oh okay.

That is definitely not an issue with DesignSPHyiscs. It is a feature of DualSPHysics. They even have a F.A.Q. for it: 

https://dual.sphysics.org/index.php/faq/#Q_12
and
https://dual.sphysics.org/index.php/faq/#Q_9

As I said in the previous comments, the simulation domain options are in Execution Parameters, at the bottom:
![image](https://user-images.githubusercontent.com/6155245/76211732-2ef01300-6207-11ea-82c6-de05d035ad81.png)

Just adjust them correctly for your case.

Please, check out your errors on Google first, ask in the DualSPHyiscs forums (forums.dual.sphysics.org) and if you detect that this is indeed an error or a bug with DesignSPHysics, not DualSPHyiscs, open an issue in here.

Hope this solves your problem. Closing as this is not an issue with DesignSPHyiscs.

**Closed by zlotny** 2020-03-09 12:11 UTC
