### ISSUE TITLE
Saving issue while "motion" is active

### ISSUE THREAD

**Issue by luizfuchs** [DualSPHysics/DesignSPHysics#28] opened 2019-11-18 16:49 UTC
Hello everyone,

I'm new at cfd simulations, so, I've decided to begin my stuidies with the sloshing tank example, from DesignSPHysiscs tutorial at youtube.

Everything was running good but when I insert "motion", the following error insistly occurs:
(P.S.: This error looks like something relative to saving the file, i wasn't able to save my file or run the mesh with the motion active (true).)

DesignSPHysics version: 0.6.0.1911-14-3
Platform: Windows-8.1-6.3.9600
FreeCAD Version: 0.18.16131 (Git)
Exception type: <class 'KeyError'>
Exception value: 'generator'
Traceback:

  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 192, in on_execute_gencase
    self.on_save_case()
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_pre_processing_widget.py", line 187, in on_save_case
    save_case(save_name, Case.the())
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\file_tools.py", line 259, in save_case
    XMLExporter().save_to_disk(save_name, case)
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\xml_exporter.py", line 86, in save_to_disk
    file.write(self.generate(case))
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\xml_exporter.py", line 75, in generate
    final_xml: str = get_template_text(self.BASE_XML).format(**self.get_adapted_case_data(case))
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\xml_exporter.py", line 66, in get_adapted_case_data
    data["wavepaddles_template"] = WavePaddlesRenderer.render(data)
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\renderers\wavepaddles_renderer.py", line 28, in render
    filtered_mkprops: list = list(filter(lambda mkprop: len(mkprop["movements"]) == 1 and mkprop["movements"][0]["generator"] and mkprop["movements"][0]["generator"]["type"] in target_types, data["mkbasedproperties"].values()))
  File "C:\Users\luiz.fuchs\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\xml\renderers\wavepaddles_renderer.py", line 28, in <lambda>
    filtered_mkprops: list = list(filter(lambda mkprop: len(mkprop["movements"]) == 1 and mkprop["movements"][0]["generator"] and mkprop["movements"][0]["generator"]["type"] in target_types, data["mkbasedproperties"].values()))

**Comment by zlotny** [comment] 2019-11-19 08:23
Thanks for reporting the issue! I'll have a look right away to see what's happening.

**Comment by zlotny** [comment] 2019-11-19 08:38
The issue is now fixed in commit 4eeaaf46eacb15eafd2eeb31365624c53808a859

For reference, I was checking if there was a "generator" inside a movement. A generator is, for example, a regular piston wave generator, or an irregular flap wave generator. I assumed that could be there because there was only one movement on the case, and generators can only be activated exclusively.

In the case you were designing you had only one movement, a regular one, which didn't have a generator. So when searching for that the software failed :)

Thanks again for reporting the issue. These things are really helpful!

**Comment by luizfuchs** [comment] 2019-11-19 22:30
Thank you for your support. In parts, it works

Well, after re-installing the software with your adjustaments, I run out the case normally...

When I set on paraview to watch the Sloshing tank, there's no movement at all, only a few particles of the fluid were moving but the "Moving tank" wasn't.

After that I decided to follow the "DualSPHysics How to set up and run: CaseWaves" to test another "moving properties"

So, I set the regular wave (Piston) and when i tried to run, the follwing message appears:

==========================
LoadDsphConfig> .../dualsphysics/bin/DsphConfig.xml
[Select CUDA Device]
[CUDA Capable device(s)]
  Detected 1 CUDA Capable device(s)
  CUDA Driver Version / Runtime Version: 10.2 / 9.2
 
Device 0: "GeForce GTX 650"
  CUDA Capability Major....: 3.0
  Global memory............: 2048 MBytes
  CUDA Cores...............: 384 ( 2 Multiprocessors, 192 CUDA Cores/MP)
  GPU Max Clock rate.......: 1059 MHz (1.06 GHz)
  Memory Clock rate........: 2500 Mhz
  Memory Bus Width.........: 128-bit
  L2 Cache Size............: 256 KBytes
  Constant memory..........: 64 KBytes
  Shared memory per block..: 48 KBytes
  Registers per block......: 65536
  Maximum threads per MP...: 2048
  Maximum threads per block: 1024
  Concurrent copy and kernel execution....: Yes with 1 copy engine(s)
  Run time limit on kernels...............: Yes
  Integrated GPU sharing Host Memory......: No
  Support host page-locked memory mapping.: Yes
  Device has ECC support..................: Disabled
  CUDA Device Driver Mode (TCC or WDDM)...: WDDM (Windows Display Driver Model)
  Device supports Unified Addressing (UVA): Yes
  Device PCI (Domain / Bus / location)....: 0 / 1 / 0
  Device supports P2P and RDMA............: No
 
[GPU Hardware]
Device default: 0  "GeForce GTX 650"
Compute capability: 3.0
Memory global: 2048 MB
Memory shared: 49152 Bytes

[Initialising JSphGpuSingle  19-11-2019 19:25:54]
ProgramFile=".../dualsphysics/bin/DualSPHysics4.4_win64.exe"
ExecutionDir=".../FreeCAD/Mod/DesignSPHysics"
XmlFile=".../CaseWaves/CaseWaves_out/CaseWaves.xml"
OutputDir=".../Waves/CaseWaves/CaseWaves_out"
OutputDataDir=".../Waves/CaseWaves/CaseWaves_out"
**Basic case configuration is loaded
**Special case configuration is loaded
Loading initial state of particles...
Loaded particles: 11138
MapRealPos(border)=(-0.101273,-0.00127279,-0.00127279)-(11.0013,0.00127279,0.706273)
MapRealPos(final)=(-0.101273,-0.00127279,-0.00127279)-(11.0013,0.00127279,0.706273)
**Initial state of particles is loaded
**2D-Simulation parameters:
CaseName="CaseWaves"
RunName="CaseWaves"
Simulate2DPosY=0
Symmetry=False
PosDouble="0: Uses and stores in single precision"
SvTimers=True
Boundary="DBC"
StepAlgorithm="Verlet"
VerletSteps=40
Kernel="Wendland"
Viscosity="Artificial"
Visco=0.010000
ViscoBoundFactor=0.000000
DensityDiffusion="None"
Shifting="None"
RigidAlgorithm="None"
FloatingCount=0
CaseNp=11138
CaseNbound=931
CaseNfixed=931
CaseNmoving=0
CaseNfloat=0
CaseNfluid=10207
PeriodicActive="None"
Dx=0.015
H=0.025456
CoefficientH=1.2
CteB=210214.281250
Gamma=7.000000
RhopZero=1000.000000
Cs0=38.3601
CFLnumber=0.200000
DtIni=0.000663602
DtMin=3.31801e-05
DtAllParticles=False
MassFluid=0.225000
MassBound=0.225000
Awen (Wendland)=859.567932
Bwen (Wendland)=-168847.218750
TimeMax=8
TimePart=0.025
Gravity=(0.000000,0.000000,-9.810000)
NpMinimum=931
RhopOut=True
RhopOutMin=700.000000
RhopOutMax=1300.000000
**Requested GPU memory for 11148 particles: 1.4 MB (0 times).
CellMode="2H"
Hdiv=1
MapCells=(219,1,14)
DomCells=(219,1,14)
DomCellCode="15_8_10"
 
BlockSize calculation mode: Fixed.
  BsForcesBound=128 (48 regs)
  BsForcesFluid=128 (54 regs)
 
**CellDiv: Requested gpu memory for 11704 particles: 0.1 MB.
**CellDiv: Requested gpu memory for 3120 cells (CellMode=2H): 0.0 MB.
 
RunMode="Pos-Single - Single-Gpu"
 
Particle summary:
  Fixed....: 931  id:(0-930)   MKs:3 (10-11,15)
  Moving...: 0
  Floating.: 0
  Fluid....: 10207  id:(931-11137)   MKs:1 (1)

Total particles: 11138 (bound=931 (fx=931 mv=0 ft=0) fluid=10207)
Total MK blocks: 4 (bound=3 (fx=3 mv=0 ft=0) fluid=1)
 
Wave paddles configuration:

*** Exception (JWavePaddleRegular::CheckConfig)
Text: Paddle without range of motion particles valid.


Finished execution (code=1).

It looks like something isn't running well on motion parameters, the casedata is exactly the same executed and shown on the youtube tutorial.

**Comment by zlotny** [comment] 2019-11-20 08:28
I see. Can you please provide the folder for the case you made on DesignSPHysics? (you can zip it and attach it here) so I can check myself if something in the GUI is doing something wrong.

Both DualSPHysics and DesignSPHysics changed a fair bit since december 2018 so I also want to check that the tutorial you watched is still working correctly.

Thank you for reporting these problems :)

**Comment by luizfuchs** [comment] 2019-11-20 14:47
Hello, I am posting the case folder for the sloshing tank and the Wave exemple.
[CaseWaves.zip](https://github.com/DualSPHysics/DesignSPHysics/files/3869761/CaseWaves.zip)
[Sloshing.zip](https://github.com/DualSPHysics/DesignSPHysics/files/3869762/Sloshing.zip)

Thanks for your support.

**Comment by zlotny** [comment] 2019-11-21 09:16
Hi there. I analysed the 2 cases and indeed I have a bug in my code!

Basically the references to an MK on the definition of a movement are wrong, they should point to an MKBound and they're pointing to an real MK (Fluid as is, Bound + 11). Ouch :(

I'll fix it right away so you can update and work with your case again.

Also, it seems by the sloshing example that you defined 2 pistons (MKBound 2 and MKBound 5) and then you deleted the MKBound 5 object. however the movement and piston were written to the XML too (wrong, another bug!). Going to fix that now as well.

**Comment by zlotny** [comment] 2019-11-21 10:03
The 2 issues are now solved. Please update DesignSPHysics and check everything works correctly now :)

Commit 6b0e62a16cd53e93b09f6810c851ea4b61d22273 fixes the reference number problem, as now MKBounds are written instead of MKReals.

Commit dc3e2daa2475a35b414858f99e4890160d24aa6c takes care of making sure that when you delete the last object with N mk the properties (like floating, movements...) that are bound to that mk dissapear.

Thank you so much for reporting these issues.

**Closed by zlotny** 2019-11-21 10:03 UTC

**Comment by luizfuchs** [comment] 2019-11-22 19:17
> Hi there. I analysed the 2 cases and indeed I have a bug in my code!
> 
> Basically the references to an MK on the definition of a movement are wrong, they should point to an MKBound and they're pointing to an real MK (Fluid as is, Bound + 11). Ouch :(
> 
> I'll fix it right away so you can update and work with your case again.
> 
> Also, it seems by the sloshing example that you defined 2 pistons (MKBound 2 and MKBound 5) and then you deleted the MKBound 5 object. however the movement and piston were written to the XML too (wrong, another bug!). Going to fix that now as well.

At the MKBound 2 and MKBound 5, i didn't delete an item, i just changed the name from MKBound 2 to MKBound 5 to run a new GenCase to see if I could solve the "old" problem... than, When I see it didn't change the problem, I rename it again to MKBound 2... it looks like the software understood as a new object and not a "tag" change.

P.S.: Everything is working fine now, the sloshing tank isn't moving as fast as your tutorial (even if I set the same parameters) but is running, at least. I will start some validation studies with some articles  by now.

Thank you very much for your support.
