### ISSUE TITLE
'Add to DSPH Simulation' does not appear

### ISSUE THREAD

**Issue by EEJGH** [DualSPHysics/DesignSPHysics#48] opened 2020-01-24 10:33 UTC
Hello everybody,

First of all, I am totally new to DesignSPHysics so apologies if this is a trivial question, I searched for the solution but could not find it...

I am following the tutorial steps on YT for hte "Hello world floating Sphere" I have my bodies created in the DSPH Case ready to be added to DSPH, but once I select them, the button which should " 'Add to DSPH Simulation' " does not appear anywhere in the GUI. I maximized the "DSPH Object Properties" window in case it was some missplacing or whatever but the button is not there...

As far as I know manually clicking on that button is a mandatory step on the whole process and has not changed... hence I cannot continue.

FreeCAD version: 0.18, release, revision number 4, 2019/10/22
DesignSPHysics version: Release 0.6.0.1911-06-15

Any advice?

Thanks in advance

**Comment by zlotny** [comment] 2020-01-24 10:41
Hi there. Thanks for submitting the issue. Can you please update to see if you're still getting the error? The version that you had is from November '19, and there was quite a bunch of changes since then.

To update the version you can just open the Macro window -> Click Addons -> Select DesignSPHysics -> Click Install/Update.

Let me know if the issue persists in the latest version.

Thanks!

**Comment by EEJGH** [comment] 2020-01-24 11:04
First I tried with the Addons manager in FreeCAD, it never worked (I let it run for half an hour, unresponsive, displayed nothing...)

Hence I tried manual installation of the Macro, so I downloaded the latest master -> DesignSPHysics did not even open.

Hence I tried with latest release -> Cannot find the button... I am trying to have a look at the code in properties_dock_widget but I do not see how the button update (visibility rule) gets triggered upon the user selecting FreeCAD elements...

**Comment by zlotny** [comment] 2020-01-24 11:17
Weird. I assume:
* You created a new case (with the New Case button)
* You created some object
* You selected the object
* The add to simulation button did not appear.

So something like this:
![image](https://user-images.githubusercontent.com/6155245/73064697-1d92b780-3ea2-11ea-94f0-913a70ff36b0.png)

About the code, you're looking for the function that is connected to FreeCAD itemSelectionChanged signal.

This is in main.py, around line 43. This function gets triggered when a selection is changed within FreeCAD and DesignSPHysics checks if the selection is a multiple one, a damping, an invalid one... etc. If it finds to be a regular object not added to the simulation it "commands" the properties widget to configure itself to show that button:

```
else:
    if not selection[0].InList:
        # Show button to add to simulation
        properties_widget.configure_to_add_single_selection()
```

That function (properties_dock_widget.py line 442 just hides and shows things:

```
self.set_add_button_text(__("Add to DSPH Simulation"))
        self.set_property_table_visibility(False)
        self.set_add_button_visibility(True)
        self.set_remove_button_visibility(False)
        self.set_damping_button_visibility(False)
```

I don't really know in which step this gets to have an error. Basically if you select a random object that is not a folder or an already known object to DesignSPHysics (like the case limits, an already added one, etc) it should just execute that last code.

Well, you already said that you manually installed the master branch version so I assume you're executing the version `0.6.0.2001-20-4`. If that's not the case it means:
* You did not update the version (I doubt it, I have faith in you :) )
* FreeCAD is messing around with library paths and loading the new main file but the old libraries.

The second case already happened here in the lab a few times, as FreeCAD seems pretty naive around loading libraries, it just loads the first thing it finds, and search in quite a weird order.

If you are sure that you have the latest version (well, you can see in mod/constants.py) the version but your GUI is showing another one, the think I found out to *just work* is to delete the FreeCAD user data folder (%appdata%/FreeCAD in Windows or $HOME/.FreeCAD on GNU/Linux).


I'm afraid I cannot give more information about that right now. I hope I gave you some pointers to find where the problem is :( 

Thank you for contributing to the project, this is indeed a weird bug.

**Comment by EEJGH** [comment] 2020-01-24 11:26
Well, thanks you a lot for all the info, I will keep on playing around, probably next step is reinstall FreeCAD, jsut in case...

But one thing... no, I do not have the .2001 version, as I said I got the latest release which is tagged as "0.6.0.1911-07-2"

Shall I try to check out master at some specific tag?

Thanks a lot!

**Comment by zlotny** [comment] 2020-01-24 11:33
Nope. Now I'm pretty sure that FreeCAD is loading old libraries cached in another place, like it happened to a colleague of mine not a long time ago here in the lab.

As you can see the latest commit on master is from 4 days ago:
![image](https://user-images.githubusercontent.com/6155245/73065950-128d5680-3ea5-11ea-8d45-87f0b171a637.png)

The version is just composed this way:

majorVersion.minorVersion.patch.YearMonth-Day-Snapshot

So for today the version should be
0.6.0.2001-24-1

And the latest version is from the 20 of January of the year 20.

If you can do it please remove that folder I said  (%appdata%/FreeCAD in Windows or $HOME/.FreeCAD on GNU/Linux). It's just guessing but I assume FreeCAD cached the files or you have 2 installations for some reason and it is loading the old libraries.

Another possible thing, but I doubt it, is that you downloaded DesignSPHysics in another place and you have the addon manager pointed to the wrong place:

![image](https://user-images.githubusercontent.com/6155245/73066134-87609080-3ea5-11ea-8dd0-b82b1a67ab50.png)

I suppose this is obvious but you should have selected at the bottom the folder in which the installation you want to run is located.


Let me know if you manage to solve this. Right know I'm pretty sure is not an issue with the code but with FreeCAD loading wrong things ; As I said, it happened before.

**Comment by EEJGH** [comment] 2020-01-24 12:54
Well... I´ll just delete everythign and fresh start it all... just in case
Will late you know

Moitas grazas!

**Comment by zlotny** [comment] 2020-01-27 07:58
I hope that solves the problem, closing it for now.

I need to investigate further on how to force FreeCAD to load the appropriate libraries in a consistent manner, as it is quite a big problem for courses and new users (the first launch of DesignSPHysics always throws an exception...)

Closing this under the assumption that deleting everything was a useful solution (but a bit drastic :( )

Grazas a ti :)

**Comment by EEJGH** [comment] 2020-01-27 12:07
Hello once again...

Freshly installed FreeCAD on Win64 from their web (i.e. not messing with brnaches and repos) -> Mod manager still seems unresponsive and finds nothing (or I am run out of pacience before it actually does)

Manually dump in the crresponding folders the Release or master version from DesignSPHysics: Release version (from November) does not show the Add to SPH sim button. Master cannot be loaded by FC (Double check the version in the constants.py file, it indeed is VERSION = "0.6.0.2001-20-4")

I will try previous master versions until one can be loaded by FC and check if the button appears...

**Comment by zlotny** [comment] 2020-01-27 12:28
That's really weird. I'll see if I can check a clean installation of Windows with FreeCAD installed. You probably won't solve anything regressing DesignSPHysics, I don't know if you refer to try previous master versions of FreeCAD.

Also we've basically done the same as you in here in the WECANET course we had a few days ago and it was just working fine for everyone (20+ people), even on their laptops.

I'll reopen this as it seems to be some obscure problem buy with this info I don't know where to proceed to fix it.

**Comment by EEJGH** [comment] 2020-01-27 12:37
Either other things around are not properly in sync (python version??) or the bug sits infornt of the computer...

**Comment by EEJGH** [comment] 2020-01-28 07:06
Solved:

FreeCAD 0.18.4 + now outdated DesignSPHysics-0.6.0.1911-07-2 -> No Button
FreeCAD 0.18.4 + master -> Button does show as expected

My problem was somethign completely unrelated in the net config which prevented the boot from running properly...

**Comment by zlotny** [comment] 2020-01-28 08:33
Wait, net config? Could be urlopen() messing this up? I'll check if DesignSPHysics works correctly even without a valid network config, as it may be an actual issue.

**Comment by zlotny** [comment] 2020-01-28 08:39
Okay, if network is not working or for some reason GitHub is down, it would now just ignore/skip the version check code.

So if this wasn't your particular problem, I still solved a bug. It seems people without Internet connection don't go to the Internet to post an issue about them having problems for not having Internet. Go figure.

Solved on commit c0bc3c1345761ba1dfb1bae0484ce54009c38322 (I guess)

**Comment by EEJGH** [comment] 2020-01-28 09:01
Yep, it was that urlopen... I just commented it out.
Regards!

**Comment by imestevez** [comment] 2023-09-05 15:21
Hello,
After you execute the macro "DesignSPHysics.FCMacro", go to the top panel and click on "View" > "Panels" > "DSPH Object Properties".

**Closed** 2023-09-19 08:09 UTC
