### ISSUE TITLE
This error appears every time step, but the processing can continue.

### ISSUE THREAD

**Issue by wangjinge1985** [DualSPHysics/DesignSPHysics#47] opened 2020-01-22 12:27 UTC
DesignSPHysics version: 0.6.0.2001-20-4
Platform: Windows-10-10.0.18362
FreeCAD Version: 0.18.4 (GitTag)
Exception type: <class 'ValueError'>
Exception value: could not convert string to float: ' 102627 3593'
Traceback:

  File "C:\Users\admin\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_simulation_widget.py", line 169, in on_fs_change
    current_value = (float(last_part_lines[-1].split("      ")[1]) * float(100)) / float(Case.the().execution_parameters.timemax)

**Comment by zlotny** [comment] 2020-01-24 10:38
Hi there. Thanks for reporting the error. This happens because the value you have put on the maximum simulation time on the execution parameters window is not a valid decimal point number, it appears.

I'll ensure in the future that the GUI doesn't let you put numbers with spaces in them.

**Comment by zlotny** [comment] 2020-01-27 08:02
I'm checking this further and... definitely my last comment is wrong. I do check that you can't input a weird number on the max simulation time...

This seems to happen because on how DesignSPHysics understand DualSPHysics logs.

Can you please finish a simulation (even with those error) and attach the Run.out file (it's in XXXX_out/Run.out) here? I'm guessing DualSPHysics is outputing something that DesignSPHysics is not able to handle right now :thinking: 

Thanks!

**Comment by wangjinge1985** [comment] 2020-01-29 08:40
Hi, attached is a run.out file. The error seems usually appeal when the processing goes to 10s time step.

**Comment by zlotny** [comment] 2020-01-29 08:41
Hi there. Seems that you forgot to attach the file.

**Comment by wangjinge1985** [comment] 2020-01-29 08:44
[Run.out.txt](https://github.com/DualSPHysics/DesignSPHysics/files/4126954/Run.out.txt)

can you see it now, I save it as .txt file.

**Comment by zlotny** [comment] 2020-01-29 08:45
Yes! Thanks :) I'll check it out to see why that error is happening.

**Comment by zlotny** [comment] 2020-01-29 10:20
Hi! The issue is solved. It only appears indeed with simulations with 10+ seconds, as the DualSPHysics output changes a bit.

However as it works as is right now I'm not updating the master branch yet, this change will be included in the next release. The commit fixing this is 2e978474ea03cb10bbc1c8b74416b9a5c5cdf4d8

Thank you so much for the issue and your time. Closing this as it is solved :)

**Closed by zlotny** 2020-01-29 10:20 UTC
