### ISSUE TITLE
Run GenCase not being excuted

### ISSUE THREAD

**Issue by Clem103** [DualSPHysics/DesignSPHysics#12] opened 2019-06-11 16:30 UTC
After import a .STL piece in FreeCAD, the Run GenCase button is still clickable but nothing happens.
It seems to onyl be working with piece designed on FreeCAD
I already took a look at issue #3, but I had no success.
There is no error code, not even a message or something.
I run on Latest designSPHysics and FreeCAD 0.18 (running on Windows 10 64-bit)

**Comment by jocdiazmuic** [comment] 2019-06-11 22:37
I can confirm that the button does nothing, without a trace or warning. Tested on Ubuntu 16.04+freecad 0.18.1+Latest designsphysics.

**Comment by CirclestheSecond** [comment] 2019-06-13 20:57
Same problem here. 
1- It does not work when I import a .stl file
or
2- When I try to change the Simulation Domain limits.

**Comment by yinyue1215** [comment] 2019-06-14 03:31
The same issue happened  to me.  After "importGEO" and adding it to DSPH simulation, the "Run GenCASE" doesn't work.

**Comment by FatimaAzhar** [comment] 2019-06-17 03:31
Same here! The error is:
> MAIN

*** Exception (JStlFile::IsBinaryFile)
Text: Cannot open the file.
File: Compound.stl

**Comment by LoreDocasar** [comment] 2019-06-21 11:22
Could you try the new version?

    https://github.com/DualSPHysics/DesignSPHysics/tree/master

Thanks for your comments!

**Comment by Clem103** [comment] 2019-06-21 18:42
Hello,
First thank you for your answer.
I tried it this evening, and it seems to be working. I do have another issue though.
I have this weird error on trying to open the GenCase. Nothing really important as i open it via Paraview, but it would be nice to fix it too. Here is the error message : (i double checked the path)
![image](https://user-images.githubusercontent.com/35854058/59944268-9b05cd80-9464-11e9-8c93-cb6f7a71af85.png)

Anyways, thank you for your answer and thanks to have fixed this because it was getting really annoying !

**Comment by LoreDocasar** [comment] 2019-06-21 19:07
Thanks for reporting the error!
I will solve it as soon as possible!

**Comment by frznaskari** [comment] 2019-07-31 09:02
hello
how to define wave paddles in designsphysics? and inlet/outlet of special dont work how to fix it?

**Comment by Rodrigo2492** [comment] 2019-08-09 23:17
Hello, in this version exits the possible introduced  porous media ?

**Comment by zlotny** [comment] 2019-09-06 08:21
@frznaskari I believe wave paddles are implemented as movements to a solid.

@Rodrigo2492 Not yet.

**Comment by GaojieSJTU** [comment] 2019-09-18 08:37
I'd like to know whether this problem has been solved. 
I met this problem as   @LoreDocasar

**Comment by GaojieSJTU** [comment] 2019-09-18 08:40
I'd like to know whether this problem has been solved.
I met this error (paraview executable path) as well. @Clem103

**Comment by zlotny** [comment] 2019-09-18 09:30
Hi there all. I assumed the problem was solved, actually, as I couldn't be able to replicate it. However i found it today and it should be fixed in 1babd6c2707556ab3c1a286deed357fbc13acd9c.

The error was not within the paraview executable or its path, but in the path of the file that it's trying to open. A path with spaces (for example, a case saved with spaces within, or inside a folder with spaces) would trigger a command line like:

`/usr/bin/paraview --data=/home/user/DesignSPHysics Cases/acase/acase_out/acase_MkCells.vtk`

However that command line has 3 arguments:
- `/usr/bin/paraview`
- `--data=/home/user/DesignSPHysics`
- `Cases/acase/acase_out/acase_MkCells.vtk`

Which is not correct. Now DesignSPHysics should always include double quotes so the command line results in this for opening paraview:

`/usr/bin/paraview --data="/home/user/DesignSPHysics Cases/acase/acase_out/acase_MkCells.vtk"`

As the issue was open for a long time I figured out I should explain exactly what was happening. Could not reproduce the issue before (and that's why I thought it already had been addresed by @LoreDocasar ) as my paths usually don't contain spaces.

Please download the lastest commit from the develop branch if you want the latest updates to the software.

I'm right now working in a big refactor and transformation of the application to prevent these issues in the future and make the app easier to develop in, so I'll update a release when this version is up. If it's going to take much longer I'll make an intermediate release with these fixes in.

PS: GenCase error should've been resolved by @LoreDocasar a while ago, just take the software from the develop branch from here.

**Closed by zlotny** 2019-09-18 09:30 UTC
